name: FrozzCore
version: '${project.version}'
main: me.thejokerdev.frozzcore.SpigotMain
api-version: 1.13
authors: [ TheJokerDev ]
description: Spigot version of FrozzCore
softdepend:
  - PlaceholderAPI
  - SkinsRestorer
  - LuckPerms
  - NickAPI

libraries:
  - org.mongodb:mongo-java-driver:3.12.13
  - org.projectlombok:lombok:1.18.24
  - commons-io:commons-io:2.11.0
  - com.zaxxer:HikariCP:3.4.5
  - org.mariadb.jdbc:mariadb-java-client:3.0.4
  - org.mongodb:mongo-java-driver:3.12.11
  - redis.clients:jedis:5.0.0-beta2
  - com.github.cryptomorin:XSeries:9.2.0
  - org.apache.commons:commons-pool2:2.11.1
  - org.slf4j:slf4j-api:2.0.7
  - org.json:json:20230618

commands:
  frozzcore:
    description: Main command of this plugin.
    aliases: [core, fcore]
